language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c 'create database bootcamp;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate
script:
  - python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: "YOUR ENCRYPTED API KEY"
