language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
services:
  - mysql
before_script:
  - mysql -e 'create database bootcamp;'
  - python manage.py makemigrations
  - python manage.py migrate
script:
  - python manage.py test
